# Generated by Django 3.2.4 on 2021-06-20 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryTaxBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('UK', 'UK'), ('PL', 'PL')], max_length=32)),
                ('income_from', models.PositiveIntegerField()),
                ('income_to', models.PositiveIntegerField(null=True)),
                ('tax_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
            ],
        ),
    ]
